os: linux
dist: jammy
language: shell
services:
  - docker

# build only the develop or release-#.# branches or tags like #.#.#
# branches:
#   only:
#     - develop
#     - /^release\-[0-9]+\.[0-9]+$/
#     - /^[0-9]+(\.[0-9]+){2}$/


install: true

jobs:
  fast_finish: true
  include:
    - name: Publish gather container in Docker Hub
      stage: deploy
      script: ./scripts/release.sh
      if: |
        fork IS false AND \
        type != pull_request AND \
        ((branch = develop) OR \
        (branch =~ ^release\-[0-9]+\.[0-9]+$) OR \
        (tag =~ ^[0-9]+(\.[0-9]+){2}$))
