os: linux
dist: bionic
language: shell
services:
  - docker
  - postgresql


# build only the develop or release-#.# branches or tags like #.#.#
branches:
  only:
    - develop
    - /^release\-[0-9]+\.[0-9]+$/
    - /^[0-9]+(\.[0-9]+){2}$/


install: true

env:
  global:
    ## Django
    - PGHOST=localhost
    - PGPORT=5432
    - DB_NAME=gather_travis
    - PGUSER=gather_user
    - PGPASSWORD=secretsecret

    - ADMIN_USERNAME=admin-test
    - ADMIN_PASSWORD=password-test

    - DJANGO_SECRET_KEY=django-secret-key-in-test-mode
    - EXPORT_MAX_ROWS_SIZE=1000
    - WEB_SERVER_PORT=9105

    - APP_NAME=Gather
    - MULTITENANCY=yes
    - DEFAULT_REALM=gather
    - REALM_COOKIE=gather-realm

    - EXTERNAL_APPS=aether-kernel,aether-odk
    - AETHER_KERNEL_TOKEN=kernel-test-token
    - AETHER_KERNEL_URL=http://kernel-test
    - AETHER_ODK_TOKEN=odk-test-token
    - AETHER_ODK_URL=http://odk-test

    - AUTO_CONFIG_CONSUMERS='true'
    - CONSUMERS_CONFIG_FILE='./conf/consumers.json'
    - TENANCY_HEADER='X-Oauth-realm'
    - TEST_VARIABLE_1='test variable 1'
    - TEST_VARIABLE_2='test variable 2'

# split jobs and only re-execute the failing one
jobs:
  fast_finish: true
  include:
    - name: Test ReactJS App
      language: node_js
      node_js: lts/*
      script: ./scripts/test-node.sh

    - name: Test Django App
      language: python
      python: '3.8'
      script: ./scripts/test-python.sh

    - name: Test concourse deployment
      stage: test
      script: docker build --pull --file gather.Dockerfile .

    - name: Publish gather container in Docker Hub
      stage: deploy
      script: ./scripts/release.sh
      if: |
        fork IS false AND \
        type != pull_request AND \
        ((branch = develop) OR \
        (branch =~ ^release\-[0-9]+\.[0-9]+$) OR \
        (tag =~ ^[0-9]+(\.[0-9]+){2}$))
