language: python

python:
  - '3.6'

services:
  - docker

before_script:
  - ./scripts/generate-credentials.sh > .env

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:
    - name: "Gather tests"
      stage: test
      script: ./scripts/test_gather.sh

    - name: "Gather release"
      stage: deploy
      script: ./scripts/release.sh

after_script:
  - ./scripts/kill_all.sh
