language: python

python:
  - '3.6'

services:
  - docker


env:
  global:
    - CACHE_DIR=$HOME/.cache


cache:
  bundler: true
  directories:
    - $CACHE_DIR


before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

script:
  - ./scripts/test_gather.sh

after_failure:
  - ./scripts/kill_all.sh


# before_deploy:
#   - pip install awscli

# deploy:
#   - provider: script
#     script: ./scripts/deploy.sh
#     skip_cleanup: true
#     on:
#       branch: develop

#   - provider: script
#     script: ./scripts/deploy.sh
#     skip_cleanup: true
#     on:
#       branch: ^\d+\.\d+(\.\d+)?(-\S*)?$
#       tags: true

#   - provider: script
#     script: ./scripts/deploy.sh
#     skip_cleanup: true
#     on:
#       branch: ^release-\d+\.\d+(\.\d+)?(-\S*)?$


after_script:
  - ./scripts/kill_all.sh
