dist: xenial

language: python
python:
  - '3.7'

services:
  - docker

install: true

before_script:
  - ./scripts/generate-credentials.sh > .env

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:
    - name: "Gather tests"
      stage: test
      script: ./scripts/test_gather.sh

    - name: "Gather release"
      stage: deploy
      script: ./scripts/release.sh
      # release only in:
        #  branch   develop
        #  branch   release-#.#
        #  tag      #.#.#
      if: (branch = develop) OR (branch =~ ^release\-[0-9]+\.[0-9]+$) OR (tag =~ ^[0-9]+(\.[0-9]+){2}$)
