dist: xenial

language: python
python:
  - '3.7'

services:
  - docker

install: true

before_script:
  - ./scripts/generate-credentials.sh > .env

# build only the develop or release-#.# branches or tags like #.#.#
branches:
  only:
    - develop
    - /^release\-[0-9]+\.[0-9]+$/
    - /^[0-9]+(\.[0-9]+){2}$/

# define stages and their execution order
stages:
  - name: test

  # release only in:
  #   - branch   develop
  #   - branch   release-#.#
  #   - tag      #.#.#
  #   - never in forks or pull requests
  - name: release
    if: |
      fork IS false AND \
      type != pull_request AND \
      ((branch = develop) OR \
      (branch =~ ^release\-[0-9]+\.[0-9]+$) OR \
      (tag =~ ^[0-9]+(\.[0-9]+){2}$))

  # Trigger deployment on GCS
  # only in:
  #   - branch   develop
  #   - branch   release-#.#
  #   - tag      #.#.#
  #   - never in forks or pull requests
  - name: deploy
    if: |
      fork IS false AND \
      type != pull_request AND \
      ((branch = develop) OR \
      (branch =~ ^release\-[0-9]+\.[0-9]+$) OR \
      (tag =~ ^[0-9]+(\.[0-9]+){2}$))

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:
    - name: "Tests"
      stage: test
      script: ./scripts/test.sh

    - name: "Release"
      stage: release
      script: ./scripts/release.sh

    - name: "Deployment"
      stage: deploy
      script: ./scripts/deploy.sh
