os: linux
dist: bionic
language: python
python:
  - '3.7'
services:
  - docker

install: true

before_script:
  - ./scripts/generate-credentials.sh > .env

# build only the develop or release-#.# branches or tags like #.#.#
branches:
  only:
    - develop
    - /^release\-[0-9]+\.[0-9]+$/
    - /^[0-9]+(\.[0-9]+){2}$/

# split jobs and only re-execute the failing one
jobs:
  fast_finish: true
  include:
    - name: "Test gather application"
      stage: test
      script: ./scripts/test.sh

    - name: "Test concourse deployment"
      stage: test
      script: docker build --pull --file gather.Dockerfile .

    - name: "Publish gather container in Docker Hub"
      stage: deploy
      script: ./scripts/release.sh
      if: |
        fork IS false AND \
        type != pull_request AND \
        ((branch = develop) OR \
        (branch =~ ^release\-[0-9]+\.[0-9]+$) OR \
        (tag =~ ^[0-9]+(\.[0-9]+){2}$))
