language: python

python:
  - '3.6'

services:
  - docker

before_script:
  - ./scripts/generate-credentials.sh > .env

script:
  - ./scripts/test_gather.sh

deploy:
  - provider: script
    script: ./scripts/release.sh
    skip_cleanup: true

after_failure:
  - ./scripts/kill_all.sh

after_script:
  - ./scripts/kill_all.sh
