version: "2.1"

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  postgres-base:
    image: postgres:9.6-alpine

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx-base:
    image: nginx:stable-alpine
    volumes:
      # config file
      - ./scripts/conf/nginx.conf.local:/etc/nginx/conf.d/default.conf

      # media folders per container
      - ./tmp/kernel/static:/media/kernel
      - ./tmp/odk/media:/media/odk

      # static folders per container
      - ./tmp/kernel/static:/static/kernel
      - ./tmp/odk/static:/static/odk
      - ./tmp/ui/static:/static/ui
    ports:
      - "80:80"


  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel-base:
    image: ehealthafrica/aether-kernel:0.8.0-rc
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      HOSTNAME: kernel.aether.local
      DEBUG: "true"

      DJANGO_SECRET_KEY: "T7cyDESETLHDz43xf3Spx9NN6UdbDkpeREfy6fwATcckcwXUUvnqfHcwyNLHrXAZ"

      # mandatory with "start" command
      # ADMIN_PASSWORD: adminadmin
      # AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24

      RDS_DB_NAME: aether-kernel
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 8000
    volumes:
      # media folder
      - ./tmp/kernel/media:/media
      # static folder
      - ./tmp/kernel/static:/var/www/static
    ports:
      - "8000:8000"
    command: start_dev


  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk-base:
    image: ehealthafrica/aether-odk:0.8.0-rc
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      HOSTNAME: odk.aether.local
      DEBUG: "true"

      DJANGO_SECRET_KEY: "T7cyDESETLHDz43xf3Spx9NN6UdbDkpeREfy6fwATcckcwXUUvnqfHcwyNLHrXAZ"

      # mandatory with "start" command
      # ADMIN_PASSWORD: adminadmin
      # AETHER_ODK_TOKEN: d5184a044bb5acff89a76ec4e67d0fcddd5cd3a1

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9000

      RDS_DB_NAME: aether-odk
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 8443
    volumes:
      # media folder
      - ./tmp/odk/media:/media
      # static folder
      - ./tmp/odk/static:/var/www/static
    ports:
      - "8443:8443"
    command: start_dev


  # ---------------------------------
  # Aether UI module
  # ---------------------------------

  ui-base:
    image: ehealthafrica/aether-ui:0.8.0-rc
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      HOSTNAME: ui.aether.local
      DEBUG: "true"

      DJANGO_SECRET_KEY: "T7cyDESETLHDz43xf3Spx9NN6UdbDkpeREfy6fwATcckcwXUUvnqfHcwyNLHrXAZ"

      # this is the right value with "start_dev" command
      # comment it out when using "start" command
      STATIC_ROOT: /code/aether/ui/static

      # mandatory with "start" command
      # ADMIN_PASSWORD: adminadmin

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9000

      RDS_DB_NAME: aether-ui
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 8004
    volumes:
      # static folder, should match STATIC_ROOT
      - ./tmp/ui/static:/code/aether/ui/static
      # if STATIC_ROOT is missing
      - ./tmp/ui/static:/var/www/static
    ports:
      - "8004:8004"
    command: start_dev


  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather-base:
    image: gather
    build:
      context: .
      dockerfile: app/Dockerfile
    stdin_open: true
    tty: true
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: gather.local
      HOSTNAME: gather.local
      DEBUG: "true"

      DJANGO_SECRET_KEY: "T7cyDESETLHDz43xf3Spx9NN6UdbDkpeREfy6fwATcckcwXUUvnqfHcwyNLHrXAZ"

      # use this value with "start_dev" command and webpack
      STATIC_ROOT: /code/gather/assets/bundles

      # use this value with "start_dev" command and without webpack
      # STATIC_ROOT: /code/gather/static

      ADMIN_PASSWORD: adminadmin

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9000

      AETHER_MODULES: "kernel,odk,"

      AETHER_ODK_TOKEN: d5184a044bb5acff89a76ec4e67d0fcddd5cd3a1
      AETHER_ODK_URL: http://odk:8443
      AETHER_ODK_URL_TEST: http://odk-test:9443

      RDS_DB_NAME: gather
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      CSV_HEADER_RULES: remove-prefix;payload.,remove-prefix;None.,replace;.;:;
      CSV_HEADER_RULES_SEP: ;
      CSV_MAX_ROWS_SIZE: 1000

      WEB_SERVER_PORT: 8005
    volumes:
      - ./app:/code
      - ./conf:/code/conf
    ports:
      - "8005:8005"
    command: start_dev

  # ---------------------------------
  # Gather Assets container
  # ---------------------------------

  gather-assets-base:
    build: ./app/gather/assets
    stdin_open: true
    tty: true
    environment:
      AETHER_MODULES: "kernel,odk,"
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_ODK_URL: http://odk:8443

      CSV_HEADER_RULES: remove-prefix;payload.,remove-prefix;None.,replace;.;:;
      CSV_HEADER_RULES_SEP: ;
      CSV_MAX_ROWS_SIZE: 1000
    volumes:
      #################################################
      #                    WARNING                    #
      # do not include the root folder as volume or   #
      # `node_modules` folder will not be available   #
      #################################################

      # include all folders and root files manually :'(
      - ./app/gather/assets/apps:/code/apps
      - ./app/gather/assets/bundles:/code/bundles
      - ./app/gather/assets/conf:/code/conf
      - ./app/gather/assets/css:/code/css
      - ./app/gather/assets/tests:/code/tests
      - ./app/gather/assets/package.json:/code/package.json
    ports:
      - "3005:3005"
    command: start_dev
