version: "2"

services:

  # ---------------------------------
  # Databases containers
  # ---------------------------------

  db-test:
    image: postgres:9.5.2

  # ---------------------------------
  # Gather2 Core container
  # ---------------------------------

  kernel-test:
    image: ehealthafrica/aether-kernel
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      TESTING: "true"
      HOSTNAME: kernel.aether.local

      RDS_DB_NAME: kernel-test
      RDS_HOSTNAME: db-test
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 9000
    depends_on:
      - db-test
    ports:
      - "9000:9000"
    depends_on:
      - db-test
    command: start_dev


  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk-importer-test:
    image: ehealthafrica/aether-odk-importer
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      TESTING: "true"
      HOSTNAME: odk.aether.local

      GATHER_CORE_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      GATHER_CORE_URL_TEST: http://kernel-test:9000

      RDS_DB_NAME: odk_importer-test
      RDS_HOSTNAME: db-test
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 9443
    depends_on:
      - kernel-test
      - db-test
    ports:
      - "9443:9443"
    depends_on:
      - db-test
      - kernel-test
    command: start_dev


  # ---------------------------------
  # UI container
  # ---------------------------------

  ui-test:
    build: gather2-ui
    environment: &ui-environment
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .gather2.local
      TESTING: "true"
      HOSTNAME: ui.gather2.local
      STATIC_ROOT: /code/gather2/ui/assets/bundles

      GATHER_ORG_NAME: eHealth Africa

      GATHER_CORE_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      GATHER_CORE_URL_TEST: http://kernel-test:9000

      GATHER_MODULES: "core,odk-importer,"

      GATHER_ODK_TOKEN: d5184a044bb5acff89a76ec4e67d0fcddd5cd3a1
      GATHER_ODK_URL_TEST: http://odk-importer-test:9443

      RDS_DB_NAME: ui-test
      RDS_HOSTNAME: db-test
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 9090
    volumes:
      #################################################
      #                    WARNING                    #
      # do not include the root folder as volume or   #
      # `node_modules` folder will not be available   #
      #                                               #
      # - ./gather2-ui:/code # DO NOT UNCOMMENT!!!    #
      #################################################

      - ./gather2-ui/conf:/code/conf
      - ./gather2-ui/gather2:/code/gather2

      - ./gather2-ui/entrypoint.sh:/code/entrypoint.sh
      - ./gather2-ui/manage.py:/code/manage.py
      - ./gather2-ui/package.json:/code/package.json
    ports:
      - "9090:9090"
    depends_on:
      - db-test
      - kernel-test
      - odk-importer-test
    command: start_dev

  # ---------------------------------
  # Gather2 Common module container
  # ---------------------------------

  common-test:
    build: gather2-common
    environment:
      TESTING: "true"
    volumes:
      - ./gather2-common:/code
    command: test
