version: "2"

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  postgres-base:
    image: postgres:9.6

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx-base:
    image: nginx:stable-alpine
    volumes:
      # config file
      - ./scripts/conf/nginx.conf.local:/etc/nginx/conf.d/default.conf

      # media folders per container
      - ./tmp/kernel:/media/kernel
      - ./tmp/odk:/media/odk
    ports:
      - "80:80"


  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel-base:
    #################################################
    #                    WARNING                    #
    #                                               #
    # uncomment this to use your local instance     #
    #                                               #
    #################################################
    image: ehealthafrica/aether-kernel:0.7.0
    # build: ../aether/aether-kernel

    stdin_open: true
    tty: true
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      DEBUG: "true"
      DJANGO_SECRET_KEY: "secret"
      HOSTNAME: kernel.aether.local

      RDS_DB_NAME: aether-kernel
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 8000
    volumes:
      #################################################
      #                    WARNING                    #
      #                                               #
      # uncomment this to use your local instance     #
      #                                               #
      #################################################
      #- ../aether/aether-kernel:/code

      # media folder
      - ./tmp/kernel:/media
    ports:
      - "8000:8000"
    command: start_dev


  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk-base:
    #################################################
    #                    WARNING                    #
    #                                               #
    # uncomment this to use your local instance     #
    #                                               #
    #################################################
    image: ehealthafrica/aether-odk:0.7.0
    # build: ../aether/aether-odk-module

    stdin_open: true
    tty: true
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      DEBUG: "true"
      DJANGO_SECRET_KEY: "secret"
      HOSTNAME: odk.aether.local

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9001

      RDS_DB_NAME: aether-odk
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 8443
    volumes:
      #################################################
      #                    WARNING                    #
      #                                               #
      # uncomment this to use your local instance     #
      #                                               #
      #################################################
      #- ../aether/aether-odk-module:/code

      # media folder
      - ./tmp/odk:/media
    ports:
      - "8443:8443"
    command: start_dev


  # ---------------------------------
  # Aether UI module
  # ---------------------------------

  ui-base:
    image: ui
    stdin_open: true
    tty: true

    #################################################
    #                    WARNING                    #
    #                                               #
    # change this value to your real aether-ui path #
    #                                               #
    #################################################
    build: ../aether/aether-ui

    environment: &ui-environment
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      DEBUG: "true"
      DJANGO_SECRET_KEY: "secret"
      HOSTNAME: ui.aether.local

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9001

      RDS_DB_NAME: aether-ui
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      STATIC_ROOT: /code/aether/ui/assets/bundles
      WEB_SERVER_PORT: 8004
    volumes: &ui-volumes
      ##################################################
      #                     WARNING                    #
      #                                                #
      # change these paths to your real aether-ui path #
      #                                                #
      ##################################################

      - ../aether/aether-ui/conf:/code/conf
      - ../aether/aether-ui/aether:/code/aether

      - ../aether/aether-ui/entrypoint.sh:/code/entrypoint.sh
      - ../aether/aether-ui/manage.py:/code/manage.py
      - ../aether/aether-ui/setup.py:/code/setup.py
      - ../aether/aether-ui/package.json:/code/package.json
    ports:
      - "8004:8004"
    command: start_dev

  # ---------------------------------
  # Webpack container
  # ---------------------------------

  webpack-ui-base:
    image: ui
    environment: *ui-environment
    volumes: *ui-volumes
    ports:
      - "3000:3000"
    command: start_webpack


  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather-base:
    image: gather
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: app/Dockerfile
    environment: &gather-environment
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: gather.local
      DEBUG: "true"
      HOSTNAME: gather.local
      STATIC_ROOT: /code/gather/assets/bundles

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9001

      AETHER_MODULES: "kernel,odk,"

      AETHER_ODK_TOKEN: d5184a044bb5acff89a76ec4e67d0fcddd5cd3a1
      AETHER_ODK_URL: http://odk:8443
      AETHER_ODK_URL_TEST: http://odk-test:9002

      RDS_DB_NAME: gather
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      CSV_HEADER_RULES: remove-prefix;payload.,remove-prefix;None.,replace;.;:;
      CSV_HEADER_RULES_SEP: ;
      CSV_MAX_ROWS_SIZE: 1000

      WEB_SERVER_PORT: 8005
    volumes: &gather-volumes
      #################################################
      #                    WARNING                    #
      # do not include the root folder as volume or   #
      # `node_modules` folder will not be available   #
      #                                               #
      # - ./:/code # DO NOT UNCOMMENT!!!              #
      #################################################

      - ./conf:/code/conf
      - ./app/gather:/code/gather

      - ./app/entrypoint.sh:/code/entrypoint.sh
      - ./app/manage.py:/code/manage.py
      - ./app/package.json:/code/package.json
    ports:
      - "8005:8005"
    command: start_dev

  # ---------------------------------
  # Webpack container
  # ---------------------------------

  webpack-gather-base:
    image: gather
    environment: *gather-environment
    volumes: *gather-volumes
    ports:
      - "3005:3005" # avoid conflict with aether-ui webpack port
    command: start_webpack
