version: "2"

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db-test:
    extends:
      file: docker-compose-base.yml
      service: postgres-base

  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel-test:
    extends:
      file: docker-compose-base.yml
      service: kernel-base
    environment:
      TESTING: "true"
      RDS_DB_NAME: aether-kernel-test
      RDS_HOSTNAME: db-test
      WEB_SERVER_PORT: 9001
    ports:
      - "9001:9001"
    depends_on:
      - db-test

  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk-test:
    extends:
      file: docker-compose-base.yml
      service: odk-base
    environment:
      TESTING: "true"
      AETHER_KERNEL_URL: http://kernel-test:9001
      RDS_DB_NAME: aether-odk-test
      RDS_HOSTNAME: db-test
      WEB_SERVER_PORT: 9002
    ports:
      - "9002:9002"
    depends_on:
      - db-test
      - kernel-test

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather-test:
    extends:
      file: docker-compose-base.yml
      service: gather-base
    environment:
      TESTING: "true"
      AETHER_MODULES: "kernel,odk,"
      AETHER_KERNEL_URL: http://kernel-test:9001
      AETHER_ODK_URL: http://odk-test:9002
      RDS_DB_NAME: gather-test
      RDS_HOSTNAME: db-test
      WEB_SERVER_PORT: 9000
    ports:
      - "9000:9000"
    depends_on:
      - db-test
      - kernel-test
      - odk-test
