version: "2.4"

networks:
  gather_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24

volumes:
  gather_database_data: {}
  gather_minio_data: {}

services:

  # ---------------------------------
  # Databases
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    volumes:
      - gather_database_data:/var/lib/postgresql/data
    networks:
      - gather_net

  redis:
    extends:
      file: ./docker-compose-base.yml
      service: redis-base
    networks:
      - gather_net

  minio:
    extends:
      file: ./docker-compose-base.yml
      service: minio-base
    volumes:
      - gather_minio_data:/data
    networks:
      - gather_net

  # ---------------------------------
  # NGINX
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    networks:
      gather_net:
        ipv4_address: 192.168.3.10
    extra_hosts:
      - aether.local:127.0.0.1
      - gather.local:127.0.0.1

  # ---------------------------------
  # Aether Kernel
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      nginx:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - gather_net
    extra_hosts:
      - aether.local:192.168.3.10
      - gather.local:192.168.3.10


  # ---------------------------------
  # Entity Extractor
  # ---------------------------------
  exm:
    extends:
      file: ./docker-compose-base.yml
      service: exm-base
    depends_on:
      redis:
        condition: service_started
    networks:
      - gather_net
    extra_hosts:
      - aether.local:192.168.3.10
      - gather.local:192.168.3.10

  # ---------------------------------
  # Aether ODK module
  # ---------------------------------

  odk:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      nginx:
        condition: service_healthy
      redis:
        condition: service_started
      kernel:
        condition: service_started
    networks:
      - gather_net
    extra_hosts:
      - aether.local:192.168.3.10
      - gather.local:192.168.3.10

  # ---------------------------------
  # Aether UI
  # ---------------------------------

  ui:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_healthy
      redis:
        condition: service_started
      kernel:
        condition: service_started
    networks:
      - gather_net
    extra_hosts:
      - aether.local:192.168.3.10
      - gather.local:192.168.3.10

  # ---------------------------------
  # Gather Assets
  # ---------------------------------

  gather-assets:
    extends:
      file: ./docker-compose-base.yml
      service: gather-assets-base
    networks:
      - gather_net

  # ---------------------------------
  # Gather
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    volumes:
      - ./.persistent_data/static/gather:/var/www/static
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_healthy
      redis:
        condition: service_started
      kernel:
        condition: service_started
      odk:
        condition: service_started
      gather-assets:
        condition: service_started
    networks:
      - gather_net
    extra_hosts:
      - aether.local:192.168.3.10
      - gather.local:192.168.3.10
