# ------------------------------------------------------------------------------
# Use this file only to develop with your local Aether images
# (not the docker hub ones), change the ${AETHER_PATH} to your current one.
#
# docker-compose -f docker-compose-local.yml build
# docker-compose -f docker-compose-local.yml up
#
# ------------------------------------------------------------------------------

version: "2.1"

networks:
  internal:
    driver: bridge

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    networks:
      - internal

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    depends_on:
      - gather
      - kernel
      - odk
      - ui
    networks:
      - internal


  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    environment:
      AETHER_KERNEL_TOKEN: ${AETHER_KERNEL_TOKEN}
      AETHER_ODK_TOKEN: ${AETHER_ODK_TOKEN}
    depends_on:
      - db
      - kernel
      - odk
    networks:
      internal:
        aliases:
          - gather.local

  # ---------------------------------
  # Gather Assets container
  # ---------------------------------

  gather-assets:
    extends:
      file: ./docker-compose-base.yml
      service: gather-assets-base
    networks:
      - internal


  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: kernel-base
    volumes:
      - ./.persistent_data/kernel/media:/media
      - ./.persistent_data/kernel/static:/var/www/static
    depends_on:
      - db
    networks:
      internal:
        aliases:
          - kernel.aether.local


  # ---------------------------------
  # ODK container
  # ---------------------------------

  odk:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: odk-base
    volumes:
      - ./.persistent_data/odk/media:/media
      - ./.persistent_data/odk/static:/var/www/static
    depends_on:
      - db
      - kernel
    networks:
      internal:
        aliases:
          - odk.aether.local


  # ---------------------------------
  # Aether UI module
  # ---------------------------------

  ui:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: ui-base
    volumes:
      - ./.persistent_data/ui/static:/var/www/static
    depends_on:
      - db
      - kernel
    networks:
      internal:
        aliases:
          - ui.aether.local
