version: "2.1"

services:

  # ---------------------------------
  # Database
  # ---------------------------------

  db-test:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base

  # ---------------------------------
  # Aether Kernel
  # ---------------------------------

  kernel-test:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    environment:
      TESTING: "true"
      MEDIA_ROOT: /tmp/
      DJANGO_SECRET_KEY: ${TEST_KERNEL_DJANGO_SECRET_KEY}

      ADMIN_USERNAME: ${TEST_KERNEL_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${TEST_KERNEL_ADMIN_PASSWORD}
      ADMIN_TOKEN: ${TEST_KERNEL_ADMIN_TOKEN}

      KERNEL_READONLY_DB_USERNAME: ${TEST_KERNEL_READONLY_DB_USERNAME}
      KERNEL_READONLY_DB_PASSWORD: ${TEST_KERNEL_READONLY_DB_PASSWORD}

      DB_NAME: aether-kernel-test
      PGHOST: db-test
      PGPASSWORD: ${TEST_KERNEL_DB_PASSWORD}

      WEB_SERVER_PORT: 9000
    volumes:
      # volumes in tests
      - ./tmp/test/kernel/media:/media
      - ./tmp/test/kernel/static:/var/www/static
      - ./tmp/test/kernel/tmp:/tmp
    ports:
      - "9000:9000"
    depends_on:
      db-test:
        condition: service_healthy
    command: start

  # ---------------------------------
  # Aether ODK
  # ---------------------------------

  odk-test:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base
    environment:
      TESTING: "true"
      MEDIA_ROOT: /tmp/
      DJANGO_SECRET_KEY: ${TEST_ODK_DJANGO_SECRET_KEY}

      ADMIN_USERNAME: ${TEST_ODK_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${TEST_ODK_ADMIN_PASSWORD}
      ADMIN_TOKEN: ${TEST_ODK_ADMIN_TOKEN}

      AETHER_KERNEL_URL: http://kernel-test:9000
      AETHER_KERNEL_TOKEN: ${TEST_KERNEL_ADMIN_TOKEN}

      DB_NAME: aether-odk-test
      PGHOST: db-test
      PGPASSWORD: ${TEST_ODK_DB_PASSWORD}

      WEB_SERVER_PORT: 9002
    volumes:
      # volumes in tests
      - ./tmp/test/odk/media:/media
      - ./tmp/test/odk/static:/var/www/static
    ports:
      - "9002:9002"
    depends_on:
      db-test:
        condition: service_healthy
      kernel-test:
        condition: service_started
    command: start

  # ---------------------------------
  # Gather
  # ---------------------------------

  gather-test:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    environment:
      TESTING: "true"
      DEBUG: null  # set to null to remove previous value
      DJANGO_SECRET_KEY: ${TEST_GATHER_DJANGO_SECRET_KEY}

      ADMIN_USERNAME: ${TEST_GATHER_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${TEST_GATHER_ADMIN_PASSWORD}

      AETHER_KERNEL_TOKEN: ${TEST_KERNEL_ADMIN_TOKEN}
      AETHER_KERNEL_URL: http://kernel-test:9000
      AETHER_ODK_TOKEN: ${TEST_ODK_ADMIN_TOKEN}
      AETHER_ODK_URL: http://odk-test:9002

      DB_NAME: gather-test
      PGHOST: db-test
      PGPASSWORD: ${TEST_GATHER_DB_PASSWORD}

      WEB_SERVER_PORT: 9005
    volumes:
      # volumes in tests
      - ./tmp/test/gather/static:/var/www/static
    ports:
      - "9005:9005"
    depends_on:
      db-test:
        condition: service_healthy
      kernel-test:
        condition: service_started
      odk-test:
        condition: service_started
    command: test

  # ---------------------------------
  # Gather Assets
  # ---------------------------------

  gather-assets-test:
    extends:
      file: docker-compose-base.yml
      service: gather-assets-base
    command: test
