services:

  # ---------------------------------
  # Database
  # ---------------------------------

  db-test:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base


  # ---------------------------------
  # Gather
  # ---------------------------------

  gather-test:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    environment:
      TESTING: "true"
      # disable profiling
      PROFILING_ENABLED: null

      # set to 1 to disable parallel execution
      TEST_PARALLEL: null

      DJANGO_SECRET_KEY: django-secret-key-in-test-mode

      ADMIN_USERNAME: testing
      ADMIN_PASSWORD: this-is-really-secret

      EXTERNAL_APPS: aether-kernel,aether-odk

      AETHER_KERNEL_TOKEN: kernel-test-token
      AETHER_KERNEL_URL: http://kernel-test

      AETHER_ODK_TOKEN: odk-test-token
      AETHER_ODK_URL: http://odk-test

      DB_NAME: gather-test
      PGHOST: db-test
      PGPASSWORD: this-is-really-really-secret.trust-me!
      DJANGO_USE_CACHE: null
      ENABLE_CONNECTION_POOL: null

      EXPORT_MAX_ROWS_SIZE: 1000

      WEB_SERVER_PORT: 9105

      CONSUMERS_CONFIG_FILE: '/code/conf/consumers.json'
      AUTO_CONFIG_CONSUMERS: "true"
      TENANCY_HEADER: 'X-Oauth-realm'

      TEST_VARIABLE_1: 'test variable 1'
      TEST_VARIABLE_2: 'test variable 2'
    depends_on:
      db-test:
        condition: service_healthy
    volumes:
      - ./app/gather/api/tests/test_consumers.json:/code/conf/consumers.json
    command: test


  # ---------------------------------
  # Gather Assets
  # ---------------------------------

  gather-assets-test:
    extends:
      file: docker-compose-base.yml
      service: gather-assets-base
    command: test
