version: "2.1"

networks:
  internal:
    driver: bridge

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    networks:
      - internal

  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    depends_on:
      - db
    networks:
      internal:
        aliases:
          - kernel.aether.local

  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base
    depends_on:
      - db
      - kernel
    networks:
      internal:
        aliases:
          - odk.aether.local

  # ---------------------------------
  # Aether UI container
  # ---------------------------------

  ui:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base
    depends_on:
      - db
      - kernel
    networks:
      internal:
        aliases:
          - ui.aether.local

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    depends_on:
      - db
      - gather-webpack
      - kernel
      - odk
    networks:
      internal:
        aliases:
          - gather.local

  # ---------------------------------
  # Gather Webpack container
  # ---------------------------------

  gather-webpack:
    extends:
      file: ./docker-compose-base.yml
      service: gather-webpack-base
    networks:
      - internal

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    depends_on:
      - gather
      - kernel
      - odk
      - ui
    networks:
      - internal
