version: "2.1"

networks:
  gather_net:
    driver: bridge

volumes:
  gather_database_data: {}
  gather_minio_data: {}

services:

  # ---------------------------------
  # Databases
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    volumes:
      - gather_database_data:/var/lib/postgresql/data
    networks:
      - gather_net

  couchdb:
    extends:
      file: ./docker-compose-base.yml
      service: couchdb-base
    networks:
      - gather_net

  redis:
    extends:
      file: ./docker-compose-base.yml
      service: redis-base
    networks:
      - gather_net

  minio:
    extends:
      file: ./docker-compose-base.yml
      service: minio-base
    volumes:
      - gather_minio_data:/data
    networks:
      - gather_net

  # ---------------------------------
  # Aether Kernel
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    depends_on:
      db:
        condition: service_healthy
    networks:
      gather_net:
        aliases:
          - kernel.aether.local

  # ---------------------------------
  # Aether ODK module
  # ---------------------------------

  odk:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
    networks:
      gather_net:
        aliases:
          - odk.aether.local

  # ---------------------------------
  # Aether CouchDB Sync module
  # ---------------------------------

  couchdb-sync:
    extends:
      file: ./docker-compose-base.yml
      service: couchdb-sync-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
    networks:
      gather_net:
        aliases:
          - sync.aether.local

  couchdb-sync-rq:
    extends:
      file: ./docker-compose-base.yml
      service: couchdb-sync-rq-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
      couchdb-sync:
        condition: service_started
    networks:
      - gather_net

  # ---------------------------------
  # Aether UI
  # ---------------------------------

  ui:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
    networks:
      gather_net:
        aliases:
          - ui.aether.local

  # ---------------------------------
  # Gather Assets
  # ---------------------------------

  gather-assets:
    extends:
      file: ./docker-compose-base.yml
      service: gather-assets-base
    networks:
      - gather_net

  # ---------------------------------
  # Gather
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
      odk:
        condition: service_started
    networks:
      gather_net:
        aliases:
          - gather.local

  # ---------------------------------
  # NGINX
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    depends_on:
      kernel:
        condition: service_started
      odk:
        condition: service_started
      couchdb-sync:
        condition: service_started
      ui:
        condition: service_started
      gather:
        condition: service_started
    networks:
      - gather_net
