version: "2.1"

networks:
  gather_net:
    driver: bridge

volumes:
  gather_database_data: {}

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    volumes:
      - gather_database_data:/var/lib/postgresql/data
    networks:
      - gather_net

  # ---------------------------------
  # Aether Kernel container
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    depends_on:
      db:
        condition: service_healthy
    networks:
      gather_net:
        aliases:
          - kernel.aether.local

  # ---------------------------------
  # Aether ODK container
  # ---------------------------------

  odk:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
    networks:
      gather_net:
        aliases:
          - odk.aether.local

  # ---------------------------------
  # Aether UI container
  # ---------------------------------

  ui:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
    networks:
      gather_net:
        aliases:
          - ui.aether.local

  # ---------------------------------
  # Gather Assets container
  # ---------------------------------

  gather-assets:
    extends:
      file: ./docker-compose-base.yml
      service: gather-assets-base
    networks:
      - gather_net

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    depends_on:
      db:
        condition: service_healthy
      kernel:
        condition: service_started
      odk:
        condition: service_started
    networks:
      gather_net:
        aliases:
          - gather.local

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    depends_on:
      kernel:
        condition: service_started
      odk:
        condition: service_started
      ui:
        condition: service_started
      gather:
        condition: service_started
    networks:
      - gather_net
