# ------------------------------------------------------------------------------
# Use this file only to develop with your local Aether images
# (not the docker hub ones), change the ${AETHER_PATH} to your current one.
#
# docker-compose -f docker-compose-local.yml build
# docker-compose -f docker-compose-local.yml up
#
# ------------------------------------------------------------------------------

version: "2.1"

networks:
  gather_local:
    driver: bridge

services:

  # ---------------------------------
  # Database
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    networks:
      - gather_local


  # ---------------------------------
  # Aether kernel
  # ---------------------------------

  kernel:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: kernel-base
    volumes:
      - ./.persistent_data/media/kernel:/media
      - ./.persistent_data/static/kernel:/var/www/static
    depends_on:
      db:
        condition: service_healthy
    networks:
      gather_local:
        aliases:
          - kernel.aether.local


  # ---------------------------------
  # Aether ODK module
  # ---------------------------------

  odk:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: odk-base
    volumes:
      - ./.persistent_data/media/odk:/media
      - ./.persistent_data/static/odk:/var/www/static
    depends_on:
      db:
        condition: service_healthy
    networks:
      gather_local:
        aliases:
          - odk.aether.local


  # ---------------------------------
  # Aether UI
  # ---------------------------------

  ui-assets:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: ui-assets-base
    networks:
      - gather_local

  ui:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: ui-base
    volumes:
      - ./.persistent_data/static/ui:/var/www/static
    depends_on:
      db:
        condition: service_healthy
    networks:
      gather_local:
        aliases:
          - ui.aether.local


  # ---------------------------------
  # Gather Assets
  # ---------------------------------

  gather-assets:
    extends:
      file: ./docker-compose-base.yml
      service: gather-assets-base
    networks:
      - gather_local


  # ---------------------------------
  # Gather
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    depends_on:
      db:
        condition: service_healthy
    networks:
      gather_local:
        aliases:
          - gather.local


  # ---------------------------------
  # NGINX
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    depends_on:
      kernel:
        condition: service_started
      odk:
        condition: service_started
      ui:
        condition: service_started
      gather:
        condition: service_started
    networks:
      - gather_local
