# ------------------------------------------------------------------------------
# Use this file only to develop with your local Aether images
# (not the docker hub ones), change the aether paths to your current ones.
#
# docker-compose -f docker-compose-local.yml build
# docker-compose -f docker-compose-local.yml up
#
# ------------------------------------------------------------------------------

version: "2"

networks:
    internal:
        driver: bridge

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db:
    extends:
      file: docker-compose-base.yml
      service: postgres-base
    networks:
      - internal

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx-base
    depends_on:
      - gather
      - kernel
      - odk
      - ui
    networks:
      - internal


  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: docker-compose-base.yml
      service: gather-base
    depends_on:
      - db
      - gather-webpack
      - kernel
      - odk
    networks:
      internal:
        aliases:
          - gather.local

  gather-webpack:
    extends:
      file: docker-compose-base.yml
      service: gather-webpack-base
    networks:
      - internal


  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel:
    build: ../aether/aether-kernel
    image: local-aether-kernel
    stdin_open: true
    tty: true
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      DEBUG: "true"
      DJANGO_SECRET_KEY: "secret"
      HOSTNAME: kernel.aether.local

      RDS_DB_NAME: aether-kernel
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 8000
    volumes:
      - ../aether/aether-kernel:/code
      # media folder
      - ./tmp/kernel:/media
    ports:
      - "8000:8000"
    command: start_dev
    depends_on:
      - db
    networks:
      internal:
        aliases:
          - kernel.aether.local


  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk:
    build: ../aether/aether-odk-module
    image: local-aether-odk
    stdin_open: true
    tty: true
    environment:
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      DEBUG: "true"
      DJANGO_SECRET_KEY: "secret"
      HOSTNAME: odk.aether.local

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9001

      RDS_DB_NAME: aether-odk
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      WEB_SERVER_PORT: 8443
    volumes:
      - ../aether/aether-odk-module:/code
      # media folder
      - ./tmp/odk:/media
    ports:
      - "8443:8443"
    command: start_dev
    depends_on:
      - db
      - kernel
    networks:
      internal:
        aliases:
          - odk.aether.local


  # ---------------------------------
  # Aether UI module
  # ---------------------------------

  ui:
    build: ../aether/aether-ui
    image: local-aether-ui
    stdin_open: true
    tty: true
    environment: &ui-environment
      CAS_SERVER_URL: https://ums-dev.ehealthafrica.org
      CSRF_COOKIE_DOMAIN: .aether.local
      DEBUG: "true"
      DJANGO_SECRET_KEY: "secret"
      HOSTNAME: ui.aether.local

      AETHER_KERNEL_TOKEN: a2d6bc20ad16ec8e715f2f42f54eb00cbbea2d24
      AETHER_KERNEL_URL: http://kernel:8000
      AETHER_KERNEL_URL_TEST: http://kernel-test:9001

      RDS_DB_NAME: aether-ui
      RDS_HOSTNAME: db
      RDS_PASSWORD: ""
      RDS_PORT: 5432
      RDS_USERNAME: postgres

      STATIC_ROOT: /code/aether/ui/assets/bundles
      WEB_SERVER_PORT: 8004
    volumes: &ui-volumes
      - ../aether/aether-ui/conf:/code/conf
      - ../aether/aether-ui/aether:/code/aether

      - ../aether/aether-ui/entrypoint.sh:/code/entrypoint.sh
      - ../aether/aether-ui/manage.py:/code/manage.py
      - ../aether/aether-ui/setup.py:/code/setup.py
      - ../aether/aether-ui/package.json:/code/package.json
    ports:
      - "8004:8004"
    command: start_dev
    depends_on:
      - db
      - kernel
      - ui-webpack
    networks:
      internal:
        aliases:
          - ui.aether.local

  ui-webpack:
    image: local-aether-ui
    environment: *ui-environment
    volumes: *ui-volumes
    ports:
      - "3004:3004"
    command: start_webpack
    networks:
      - internal
