apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gather
  labels:
    app: gather
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: container.dev.k8s.eha.to
      labels:
        app: gather
    spec:
      containers:
      - name: gather
        image: 387526361725.dkr.ecr.eu-west-1.amazonaws.com/gather-on-aether-dev:latest
        args:
        - start
        ports:
        - containerPort: 8000
        env:
        - name: CAS_SERVER_URL
          value: https://ums-dev.ehealthafrica.org
        - name: CSRF_COOKIE_DOMAIN
          value: .gather2.org
        - name: CSRF_TRUSTED_ORIGINS
          value: .gather2.org
        - name: RDS_DB_NAME
          value: gather
        - name: RDS_PORT
          value: "5432"
        - name: WEB_SERVER_PORT
          value: "8000"
        - name: AETHER_KERNEL_URL
          value: "https://kernel-dev-goa.gather2.org"
        - name: AETHER_MODULES
          value: kernel,odk
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-goa-secrets
              key: odk_admin_password
        - name: AETHER_KERNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: dev-goa-secrets
              key: kernel_token
        - name: AETHER_ODK_TOKEN
          valueFrom:
            secretKeyRef:
              name: dev-goa-secrets
              key: odk_token
        - name: AETHER_ODK_URL
          value: "https://odk-dev-goa.gather2.org"
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: dev-database
              key: user
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-database
              key: password
        - name: RDS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: dev-database
              key: host
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        stdin: true
        tty: true
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        - name: gather-nginx-config
          mountPath: /etc/nginx/conf.d
      imagePullSecrets:
        - name: regsecret
      volumes:
        - name: static-assets-volume
          emptyDir: {}
        - name: gather-nginx-config
          configMap:
            name: gather-nginx-config
      restartPolicy: Always
