# Default values for gather.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: nginx
  tag: stable-alpine
  pullPolicy: IfNotPresent
gather:
  repository: "387526361725.dkr.ecr.eu-west-1.amazonaws.com/gather-on-aether-dev"
name: gather
project: project
release: 2.1.1
additonal_env_vars: false
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80
environment: "dev"
ums_url: ums-dev
domain: gather2.org
trusted_origins: .ehealthafrica.org,.gather2.org
namespace:
  create: false
application:
  secret: secrets
  data_mount: /data
database:
  secret: database-credentials
provider:
  aws: false
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:387526361725:certificate/dcd71c49-1b5b-4b19-bd2d-6de98a3f6477"
    alb.ingress.kubernetes.io/security-groups: "alb-ingress-controller.dev.k8s.eha.to"
